Consensys/corset

src/stdlib.lisp

This replaces the redundant type annotations `@loobean` and `@boolean` with their shorter counterparts `@loob` and `@bool`.
**NOTE**: there remain missing `binary` annotations which will be fixed separately in a subsequent PR.

Replace `@loobean` and `@boolean`

---

src/stdlib.lisp

In the standard library I believe the `binary` type annotation can be added in a small number of places.  For example, `~and` is guaranteed to return a `binary` value because it uses `~` on its return value, etc.

Add missing `binary` type annotations

---

src/compiler/common.rs

These operations are required for field agnosticity.  That is, where a virtual field is spread across several actual fields (i.e. because its bitwidth is larger than what is provided by the prime field).

Document vector operations.

---

src/stdlib.lisp

The purpose of this warning is simply to document that for functions are unsafe in certain contexts.  Specifically, `and!`, `or`, `all!` and `any` all compile down to `+`.  Therefore, they are unsafe when their arguments can be arbitrarily large as they are subject to overflow.

Add relevant warning on the corset stdli

---

Cargo.toml
src/main.rs
src/structs/handle.rs

This now enables support for binary output serialisation.  However, at this stage, it remains hidden behind a feature flag.  The reason for this is simply that it currently alter's output in the non-JSON path as well.  The need for this arose from the mechanism required for serialising handles.

Binary Output Serialisation to JSON

---

src/transformer/inverses.rs

This applies a patch suggested by Franklin for improving the translation of `NORM(e)` terms.  Specifically, when `e` is known to be `binary` then we actually don't need to create an inverse column.  Instead, we can use `e` directly as we already know its normalised.

Improved translation for `NORM(e)` #91

---

src/compiler/generator.rs

fix: remove old `to_string` invokation

---

src/column.rs

Previously, columns marked as `:bytes` were displayed in the inspector in _little endian_ form.  However, this was awkward for comparing with normal hexadecimal values.  For example, `0x1023` was shown as `23 10`.
Therefore, have changed the display option to show `:bytes` in big endian notation.  Thus, the example above shows as `10 23`.

Display `:bytes` in big endian

---

src/compiler/parser/parser.rs

This updates the default base for the column(s) arising from an interleaved constraint to be hexadecimal rather than decimal.  This now follows the convention used in e.g. `defcolumns` which also defaults to hex.

Fix Default Base for Interleaved Constraints

---

src/exporters/convert.rs
src/main.rs

fix: rendering of columns in `convert`

---

src/import.rs
tests/models.rs

This updates the testing framework to support padding.  In particular, it now always padds the first row with zeros.  At some point, we'll need to support minimum length padding based on e.g. range constraints.

Update testing framework to support padding

---

src/column.rs

Remove `Column::shift`

---

src/stdlib.lisp

This puts through a simple fix for the standard library.

Fix for `eq!` typing in `stdlib.lisp`

---

src/compiler/generator.rs
src/compiler/node.rs
src/exporters/debugger.rs

This prevents "future" or positive spillage from being reported as spillage.  In essence, this feature is removed completely.

Optimise spillage by removing `future_spilling()`

---

src/compiler/generator.rs
src/compiler/node.rs
src/exporters/debugger.rs

This reverts commit 90a87edb533523f875b463a720b0546be074f22c.

Revert "Optimise spillage by removing `future_spilling()`"

---

src/column.rs
src/errors.rs
src/transformer/selectors.rs

This fixes #161 and problems related to the use of constant expressions within lookups.  Specifically, such expressions were being incorrectly expanded into the `<prelude>` module.  To resolve this, the logic for determining the target (resp. source) modules for a lookup has been expanded.

161 bug nil spilling used in compute expression function

---

Cargo.lock
src/compiler/common.rs
src/main.rs

A problem was arising related to the typing of vector operations. Specifically, it was being considered that e.g. a `binary` value added to another `binary` value produced a `binary` value.  This corrects those problems, but there remain some mysteries around typing.

fix: Incorrect typing of vector operations

---

src/compiler/types.rs
src/transformer/nhood.rs

This applies to all integer types, including `byte` and `nibble`. However, `binary` constraints are treated different and use vanishings constraints instead.
There also remains an outstanding issue related to perspectives, in that the perspective selector is not being applied.  This will be resolved separately in #101.

feat: Implement `byte@prove` using range constraints

---

src/compiler/node.rs

This puts in place a custom serializer for `ColumnRef` so that it can correctly be serialised into `json`.  The reason is that `ColumnRef`s are used as keys into a `HashMap`, and therefore they require a custom serialiser.

fix: Custom `Serializer` for `ColumnRef`

---

src/compiler/node.rs
src/structs/handle.rs

This puts in a minor correction in order to keep consistency with serlisation of `Handle`.

Minor correction for serialisation of `ColumnRef`

---

src/compiler/generator.rs

This fixes an issue that arises for a singleton `reduce`.  That is a `reduce` over a list with only a single element.  To be fair, this is not something that should actually be done in practice.

Fix for Singleton Reduce

---

src/compiler/common.rs
src/compiler/generator.rs
src/compiler/node.rs

This puts in place additional layers of check to try and prevent wierd situations arising from the use of `for`.

fix: Error when missing reduce

---

src/compiler/generator.rs
src/compiler/parser/definitions.rs
src/compiler/tables.rs
src/structs/handle.rs
src/transformer/ifs.rs

This puts through a fix for the generated `define.go` where certain unused columns were being turned into Go declarations.  Since these declarations were not then being used, Go was reporting an error (since it is very strict about this).

fix: Unused Declaration for Array Columns (`define.go`)

---

src/column.rs
src/compiler/generator.rs
src/compute.rs
src/exporters/wizardiop.rs
src/transformer.rs
src/transformer/ifs.rs
src/transformer/nhood.rs

The problem was that lists were not being raised correctly out of expressions and, in particular, this was causing a problem with perspective selectors.

Fix: Incorrect Handling of Perspective Selectors

---

src/compiler/generator.rs

This was accidentally left in after a previous fix.

Remove debugging code

---

Cargo.lock
Cargo.toml
src/inspect/mod.rs

It seems that, for reasons unknown, two distinct versions of ratatui were being compiled against.  This was causing a clash, leading to compilation failure.  This fix moves `corset` to fix on ratatui `v0.27` which appears to resolve the issue.

Fixes for `ratatui` dependency issue

---

src/exporters/besu.rs
src/inspect/mod.rs

This reworks the generate putters to use a more uniform style and, furthermore, to perform sanity checking on every value.  These now generates `Trace.java` files which write columns with the expected byte-width (e.g. `1` byte for `i8`, `2` bytes for `i16`, `4` bytes for `i32`) in all cases.

Rework generated "putters".

---

Cargo.toml
src/compiler/generator.rs
src/compiler/node.rs
src/main.rs
src/structs/handle.rs

Previously, the ability to generate `JSON` binfiles was hidden behind a build feature.  Hence, you needed to build the binary specifically for generating `JSON` binfiles.  The primary reason for this is that supporting both `RON` and `JSON` formats in the same binary required breaking changes to the format.  However, the time has come to address this and support both formats.  At this time, `RON` remains the default choice --- but this will be deprecated in the very near future.

feat: Support `RON` and `JSON` bin formats

---

src/inspect/mod.rs
src/main.rs

This completely hides values for columns in inactive perspectives. However, should one want to, the original behaviour can be toggled using 'p' for that module.

feat: Support Perspective "blanking"

---

src/cgo.rs
src/compiler/node.rs
src/main.rs
src/structs/handle.rs

This switches over the default format for the `bin` files from using Rusty Object Notation (RON) to JSON.

feat: Switch default `bin` format from `RON` to `JSON`

---

src/inspect/mod.rs

Column names were being incorrectly truncated when the names were long. This was caused by a marginally incorrect width calculation, which is now fixed.

Fix: Truncated Column Names

---

src/check.rs
tests/models.rs

This updates the reporting for the `check` command with respect to perspectives.  Specifically, the output now resembles that of the inspector more closely by including perspective identifiers when relevant.

fix: Update `check` reporting for perspectives

---

.github/workflows/release.yml
.github/workflows/rust.yml
Cargo.lock

This updates the release action to include the `--locked` flag.  This shold prevent clashes as new versions of upstream libraries are released.

Updating release action

---

.github/workflows/release.yml

This hopefully fixes a typo in the `release.yml` file which was not caught by precommit (?)

Update `release` action

---

.github/workflows/release.yml
.github/workflows/rust.yml

This updatest the github `release.yml` action to support the latest version of Rust.  This is required for the ratatui dependency.  At this stage, I did not figure out how to "lock" the dependencies for the release build.

fix: Update Github Release Action

---

.github/workflows/release.yml

This removes the `--locked` directive from the `release` action build because, despite several attempts, I cannot get this to work.

Remove `--locked` from `release` action

---

.github/workflows/rust.yml
Cargo.lock
build.rs
tests/models.rs

This corrects the placement of `CORSET_TEST_LIMIT` in the build action.

Correct Build Action

---

src/transformer/ifs.rs
tests/issue241_c.lisp
tests/issue241_d.lisp
tests/issue241_e.lisp
tests/models.rs

This reworks the `ifs` transform to use a simpler approach which should be easier to understand and maintain.  Following the original `corset` implementation, this applies some optimisations in various cases.

fix: Rework `ifs` transform

---

src/exporters/besu.rs
src/exporters/besu_trace_columns.java
src/main.rs

This allows a custom class name to be used in place of `Trace.java` when desired.

Support custom class name for trace file.

---

Cargo.lock
src/exporters/besu_trace_columns.java

This puts in place a simple fix for the trace file template related to the ability to customise the class name generated.

fix: trace file template (#277)

---

src/compiler/generator.rs

This adjusts the minimum expected arity for `begin` statements to allow them to be empty.  The reason for this is that, in practice, we may have a `begin` statement stuffed only with `debug` constraints (which are physically removed unless the `--debug` switch is provided).

feat: Allow empty `(begin ..)`

---

src/exporters/besu.rs
src/exporters/besu_trace_columns.java

The generated column setters were invalid because they were iterating over BesuColumn instances which didn't (previously) include the `class` attribute.

fix: column setters in trace template

---

src/exporters/besu.rs

This slightly improves the error reporting in generate `Trace.java` files, where previously the register names were being passed to the exception being thrown.  Instead, we now use the column name (optionally with perspective).

feat: improved error reporting in generated `Trace.java`

---

Cargo.lock
src/check.rs
src/column.rs

Previously, there was no proper checking for failing constraints when the domain of the constraint was `-1`.  This is an unexpected bug within the tool.

Support Checking for Negative Domain

---

Cargo.lock
src/column.rs

This allows large numbers to be shown as negatives within the inspector. That should improve readability.

feat: show negative numbers in Inspector

---

src/inspect/mod.rs

This updates the key binding for clearing the filter in the inspector from "F" to "#".  This just prevents accidentally clearing the filter when doing something else.

feat: update inspector key binding for "clear filter"
